// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/video/video.proto

package videopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_proto_video_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type VideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	mi := &file_proto_video_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_proto_video_video_proto_rawDescGZIP(), []int{1}
}

func (x *VideoChunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_video_video_proto protoreflect.FileDescriptor

const file_proto_video_video_proto_rawDesc = "" +
	"\n" +
	"\x17proto/video/video.proto\x12\x05video\")\n" +
	"\fVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"6\n" +
	"\n" +
	"VideoChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2G\n" +
	"\fVideoService\x127\n" +
	"\vStreamVideo\x12\x13.video.VideoRequest\x1a\x11.video.VideoChunk0\x01B4Z2github.com/khbdev/amaliy-proto/proto/video/videopbb\x06proto3"

var (
	file_proto_video_video_proto_rawDescOnce sync.Once
	file_proto_video_video_proto_rawDescData []byte
)

func file_proto_video_video_proto_rawDescGZIP() []byte {
	file_proto_video_video_proto_rawDescOnce.Do(func() {
		file_proto_video_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_video_proto_rawDesc), len(file_proto_video_video_proto_rawDesc)))
	})
	return file_proto_video_video_proto_rawDescData
}

var file_proto_video_video_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_video_video_proto_goTypes = []any{
	(*VideoRequest)(nil), // 0: video.VideoRequest
	(*VideoChunk)(nil),   // 1: video.VideoChunk
}
var file_proto_video_video_proto_depIdxs = []int32{
	0, // 0: video.VideoService.StreamVideo:input_type -> video.VideoRequest
	1, // 1: video.VideoService.StreamVideo:output_type -> video.VideoChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_video_video_proto_init() }
func file_proto_video_video_proto_init() {
	if File_proto_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_video_proto_rawDesc), len(file_proto_video_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_video_proto_goTypes,
		DependencyIndexes: file_proto_video_video_proto_depIdxs,
		MessageInfos:      file_proto_video_video_proto_msgTypes,
	}.Build()
	File_proto_video_video_proto = out.File
	file_proto_video_video_proto_goTypes = nil
	file_proto_video_video_proto_depIdxs = nil
}
